# 08/05/25

In [ ]:
pandas === very big
when you apply banking companies

- In Pandas we can join two dataframes

    - merge

    - join

    - concat

**merge**

- it is under pandas the function: pd.merge

- it is similar to SQL joins

- you can join with specific columns

In [4]:
import pandas as pd

In [6]:
d1={'ID':[1,2,3],'Name':['Chandu','Pawan','Bansal']}
d2={'ID':[1,2,4],'Age':[20,25,30]}
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)

In [8]:
df1

   ID    Name
0   1  Chandu
1   2   Pawan
2   3  Bansal

In [10]:
df2

   ID  Age
0   1   20
1   2   25
2   4   30

In [12]:
pd.merge(df1,df2,on='ID',how='inner')

   ID    Name  Age
0   1  Chandu   20
1   2   Pawan   25

In [14]:
pd.merge(df1,df2,on='ID',how='outer')

   ID    Name   Age
0   1  Chandu  20.0
1   2   Pawan  25.0
2   3  Bansal   NaN
3   4     NaN  30.0

In [16]:
pd.merge(df1,df2,on='ID',how='left')

   ID    Name   Age
0   1  Chandu  20.0
1   2   Pawan  25.0
2   3  Bansal   NaN

In [18]:
pd.merge(df1,df2,on='ID',how='right')

   ID    Name  Age
0   1  Chandu   20
1   2   Pawan   25
2   4     NaN   30

In [ ]:
## Homework

df1.join(df2)

pd.concat([df1,df2])