# 07/05/25

In [1]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],'Age':[np.nan,22,25,27],'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [3]:
df.to_csv('data_missing.csv',index=False)

In [5]:
pd.read_csv('data_missing.csv')

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [11]:
import numpy as np
import pandas as pd
Data1={'Names':['Ramesh','Suresh','Sathish',None],'Age':[None,22,25,27],'City':['Pune','Pune',None,'Hyd']}
df1=pd.DataFrame(Data1)
df1

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [13]:
df1.to_csv('data_missing1.csv',index=False)

In [15]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [17]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

**isnull**

In [20]:
df.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [22]:
df1.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [24]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [26]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [29]:
df.fillna(30)  # Not Recomended

     Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

In [31]:
df1.fillna(30)

     Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

- the above one is we are filling randomly

- all the columns are filled with random number

- It is not a good approach because in a data we have different data types

In [34]:
df.fillna('Hyd')

     Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

In [36]:
df1.fillna('Hyd')

     Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

**What is the difference between np.nan and None**

In [39]:
np.nan+5

nan

In [41]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [43]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [45]:
arr1

array([ 1.,  2., nan,  3.])

In [47]:
arr2

array([1, 2, None, 3], dtype=object)

In [49]:
np.nansum(arr1),np.sum(arr1)

(6.0, nan)

In [51]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents **float type**

- None represents **Object type**

- if data operations related to Maths then nan format is better

**Fill the value based on column**

In [55]:
# df.fillna()
df['Names'].fillna('Manish')

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

In [57]:
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [59]:
df['Age'].fillna(20)

0    20.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [61]:
df['Age'].fillna('20')

0      20
1    22.0
2    25.0
3    27.0
Name: Age, dtype: object

In [63]:
df['Age'].fillna(20).values

array([20., 22., 25., 27.])

In [65]:
df['Age'].fillna('20').values

array(['20', 22.0, 25.0, 27.0], dtype=object)

In [67]:
df['Age1']=df['Age'].fillna(20).values
df['Age2']=df['Age'].fillna('20').values

In [69]:
df

     Names   Age  City  Age1  Age2
0   Ramesh   NaN  Pune  20.0    20
1   Suresh  22.0  Pune  22.0  22.0
2  Sathish  25.0   NaN  25.0  25.0
3      NaN  27.0   Hyd  27.0  27.0

In [71]:
df.dtypes

Names     object
Age      float64
City      object
Age1     float64
Age2      object
dtype: object

- because of one value total data type is changed

- we can convert one data type column to another data type **astype**

In [74]:
df['Age2']=df['Age2'].astype('float')

In [76]:
df.dtypes

Names     object
Age      float64
City      object
Age1     float64
Age2     float64
dtype: object

**Fill with Method**

In [79]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],'Age':[np.nan,22,25,27],'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

- pad

- bfill

- ffill

- backfill

In [82]:
df.fillna(method='pad')

C:\Users\HP\AppData\Local\Temp\ipykernel_9100\196241153.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [84]:
import warnings
warnings .filterwarnings('ignore')
df.fillna(method='pad')

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [86]:
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [88]:
s='U+200B (ZERO WIDTH SPACE)'
s1=''
for i in s:
    if i.isdigit():
        s1=s1+i
int(s1)

200

In [90]:
import warnings
warnings .filterwarnings('ignore')
df.fillna(method='bfill')

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [92]:
import warnings
warnings .filterwarnings('ignore')
df.fillna(method='ffill')

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [94]:
import warnings
warnings .filterwarnings('ignore')
df.fillna(method='backfill')

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [106]:
df.fillna(method='pad',axis=1)

     Names     Age  City
0   Ramesh  Ramesh  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

In [ ]:
# pad-ffill
# bfill-backfill

**Mean-Median-Mode**

- insted of filling with random values

- we can use mean median and mode also

- For Numerical columns use mean and Median

    - if Data outliers are there use **Median**

- For categorical columns use **Mode**

In [97]:
# First calculate median
# Then fill with median
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [99]:
round(df['Age'].mean(),2)

24.67

**KNNImputer**

- KNN: K nearest neigbours

- instead of taking all the data values average

- we can take only specific values average

- thats why the name is called as Nearest Neighbours

- Hyper parameter: the argument which user can provide

- here k is hyper parameter

- which means the user can decide how many neighbours he can choose

- it is under sklearn

    - class name imputer

        - method name KNNImputer

In [103]:
data1={'A':[1,2,3,4,5,np.nan,7],'B':[11,22,np.nan,47,55,77,7],'C':[21,10,3,4,np.nan,66,7]}
df2=pd.DataFrame(data1)

In [105]:
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=2)
knn.fit_transform(df2)

array([[ 1. , 11. , 21. ],
       [ 2. , 22. , 10. ],
       [ 3. , 51. ,  3. ],
       [ 4. , 47. ,  4. ],
       [ 5. , 55. ,  3.5],
       [ 4.5, 77. , 66. ],
       [ 7. ,  7. ,  7. ]])

In [107]:
(4+5+7)/3

5.333333333333333

In [109]:
(1+2+7)/3

3.3333333333333335

- How it is deciding neigbours: Euclidian distance

- give the categorical data : It is works or not

In [ ]:
10days individual
1day 2hours
bullets
wed sql
transforamtions

# 08/05/25

In [ ]:
idea-1: filling with random value = df.fillname(<random value)
idea-2: filling with rv based on column = df[<col>].fillname(<rv>)
idea-3: filling with some pattern using a method: df.fillna(<method>)
idea-4: filling with m-m-m based on column = df[<col>].fillname(<m>or<m>or<m>)
idea-5: filling with average value only selected neighbours
idea-6: filling with a value based on correlation with another columns

**Mean-Median-Mode**

In [134]:
Data1=pd.DataFrame({'Names':['Ramesh','Suresh','Sathish',None],'Age':[None,22,25,27],'City':['Pune','Pune',None,'Hyd']})
age_mean=Data1['Age'].mean()
print('age_mean:',age_mean)
Data1['Age'].fillna(age_mean)
Data1

age_mean: 24.666666666666668

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [140]:
city_mode=Data1['City'].mode()
Data1['City'].fillna(city_mode)

0    Pune
1    Pune
2     NaN
3     Hyd
Name: City, dtype: object

In [144]:
age_mean

24.666666666666668

In [146]:
city_mode

0    Pune
Name: City, dtype: object

In [148]:
city_mode.values[0]

'Pune'

- in future sometimes if we direct imput mode value we will get error

- mode is coming as series

- mean is coming as fixed values

- so first convert series to fixed value then apply it

**impute class**

- under sklearn we have impute class is there

In [151]:
from sklearn import impute

In [153]:
dir(impute)

['KNNImputer',
 'MissingIndicator',
 'SimpleImputer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_knn',
 'typing']

**KNN Immputer**

- k-Nearest Neighbours

- Where k = hyper parameter which means the user can change

- Idea: Instead of taking all the samples average

    - First fix the neighbours number i.e. k

    - Then find the neighbours using distance metric

    - Then take the average of those samples to fill the missing value

In [155]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [157]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

- weights = 'uniform'

- uniform: equal priority to every one

- sklearn = class

- prepocessing/impute = method

In [160]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])